- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
  - name: "Adding Docker apt key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "Adding Docker apt repository"
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      filename: docker

  - name: "Installing Dependencies"
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - "aptitude"
      - "apt-transport-https"
      - "ca-certificates"
      - "curl"
      - "software-properties-common"
         
  - name: "Installing docker-ce"
    apt:
      name: "docker-ce"
      update_cache: yes

  - name: "Starting Docker"
    service:
      name: docker
      state: started
